spring:
  datasource:
    url: jdbc:mysql://192.168.1.156/zone?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
server:
  port: 8080
logging:
  level:
    cn.cloudtop.zone: debug
    org.hibernate: error
    org.eclipse.jetty: error
    org.springframework: error
    springfox.documentation: error
    java.sql: error
  file: /var/logs/zone/zone.log
service:
  name: zone-service
  version: v1
  desc: provide country,province,city,district/country.
  creator: jackie.han@cloudtopcn.com
registry:
  url: http://192.168.1.156/
  port: 2379
