spring:
  datasource:
    url: jdbc:mysql://192.168.0.133/zone?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 192.168.0.133
    port: 6379
    password:
    database: 5
    timeout: 0
    pool:
      max-active: 18
      max-idle: 8
      max-wait: -1
      min-idle: 0
  mvc:
    throw-exception-if-no-handler-found: true
server:
  port: 8080
logging:
  level:
    cn.cloudtop.zone: debug
    org.hibernate: error
    org.eclipse.jetty: error
    org.springframework: error
    springfox.documentation: error
    java.sql: error
  file: /var/logs/zone/zone
info:
  app:
    name: zone-service
    description: provide country,province,city,district/country operators.
    version: v1
    creator: jackie.han@cloudtopcn.com
registry:
  url: http://192.168.0.133:2379/
